import type { Metadata } from "next";

import Head from 'next/head'
import seosettings from "../../seosettings";

import Header from '../../components/Header'
import Menu from '../../components/Menu'
import Footer from '../../components/Footer'
import NewsContent from '../../components/NewsContent'

export const dynamicParams = false

export async function generateStaticParams() {
  
  const posts = await fetch('http://localhost:3000/api/news').then((res) => res.json()).then(data => data.news)

  return posts.map((post) => {
    return {
      id: encodeURI(post.title)
    }
  })
}


export default function IndexPage({ params: {id} }) {

  return (async() => {

    let data;
    let response = await fetch('http://localhost:3000/api/news', {
      method: 'PATCH',
      body: JSON.stringify({
          title: decodeURI(id).replaceAll('%3A',':'),
      }),
      headers: {
          'Content-type': 'application/json'
      }
  })

  response = await response.json()

  data = await JSON.parse(JSON.stringify(response));

  return <div>
              <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css2?family=Chocolate+Classical+Sans&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Ubuntu+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet"></link>
                <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet"></link>

              </Head>
            <div>
              <Menu/>
            </div>
              <Header/>
              <NewsContent data={data}/>
              <Footer/>
          </div>


  })()
}

export const metadata: Metadata = seosettings.pizzas;