import type { Metadata } from "next";
import Head from 'next/head'

import Header from './components/Header'
import MiniCart from './components/MiniCart'
import Content from './components/Content'

export default function IndexPage() {
  return <div>
            <Head>
              {/* <title>Create Next App</title> */}
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
          <div>
            <MiniCart/>
          </div>
          <Header/>
          <Content/>
          </div>
}

export const metadata: Metadata = {
  title: "Redux Toolkit",
};
